from django import forms

class SignupForm(forms.Form):
	UserName = forms.CharField(label = "用户名 (4至20位)", max_length = 20, min_length = 4)
	PassWord = forms.CharField(label = "密码 (4至20位)", max_length = 20, min_length = 4, widget = forms.PasswordInput())
	InvitionCode = forms.CharField(label = "邀请码(6位)", max_length = 6, min_length = 6)

class LoginForm(forms.Form):
	UserName = forms.CharField(label = "用户名", max_length = 20, min_length = 4)
	PassWord = forms.CharField(label = "密码", max_length = 20, min_length = 4, widget = forms.PasswordInput())

class UserMgrForm(forms.Form):
	UserName = forms.CharField(label = "用户名", max_length = 20, min_length = 4)
	Recharge = forms.IntegerField(label = "充值", min_value = 0, initial = 0)
	Deposit = forms.IntegerField(label = "提现", min_value = 0, initial = 0)
	AddCredit = forms.IntegerField(label = "增加信用", min_value = 0, initial = 0)
	DecCredit = forms.IntegerField(label = "降低信用", min_value = 0, initial = 0)

class TransferForm(forms.Form):
	UserName = forms.CharField(label = "用户名", max_length = 20, min_length = 4)
	Money = forms.IntegerField(label = "金额", min_value = 0, initial = 0)

class BetOneForm(forms.Form):
	num1 = forms.IntegerField(label = "01", min_value = 0, initial = 0)
	num2 = forms.IntegerField(label = "02", min_value = 0, initial = 0)
	num3 = forms.IntegerField(label = "03", min_value = 0, initial = 0)
	num4 = forms.IntegerField(label = "04", min_value = 0, initial = 0)
	num5 = forms.IntegerField(label = "05", min_value = 0, initial = 0)
	num6 = forms.IntegerField(label = "06", min_value = 0, initial = 0)
	num7 = forms.IntegerField(label = "07", min_value = 0, initial = 0)
	num8 = forms.IntegerField(label = "08", min_value = 0, initial = 0)
	num9 = forms.IntegerField(label = "09", min_value = 0, initial = 0)
	num10 = forms.IntegerField(label = "10", min_value = 0, initial = 0)
	num11 = forms.IntegerField(label = "11", min_value = 0, initial = 0)
	num12 = forms.IntegerField(label = "12", min_value = 0, initial = 0)
	num13 = forms.IntegerField(label = "13", min_value = 0, initial = 0)
	num14 = forms.IntegerField(label = "14", min_value = 0, initial = 0)
	num15 = forms.IntegerField(label = "15", min_value = 0, initial = 0)
	num16 = forms.IntegerField(label = "16", min_value = 0, initial = 0)
	num17 = forms.IntegerField(label = "17", min_value = 0, initial = 0)
	num18 = forms.IntegerField(label = "18", min_value = 0, initial = 0)
	num19 = forms.IntegerField(label = "19", min_value = 0, initial = 0)
	num20 = forms.IntegerField(label = "20", min_value = 0, initial = 0)
	num21 = forms.IntegerField(label = "21", min_value = 0, initial = 0)
	num22 = forms.IntegerField(label = "22", min_value = 0, initial = 0)
	num23 = forms.IntegerField(label = "23", min_value = 0, initial = 0)
	num24 = forms.IntegerField(label = "24", min_value = 0, initial = 0)
	num25 = forms.IntegerField(label = "25", min_value = 0, initial = 0)
	num26 = forms.IntegerField(label = "26", min_value = 0, initial = 0)
	num27 = forms.IntegerField(label = "27", min_value = 0, initial = 0)
	num28 = forms.IntegerField(label = "28", min_value = 0, initial = 0)
	num29 = forms.IntegerField(label = "29", min_value = 0, initial = 0)
	num30 = forms.IntegerField(label = "30", min_value = 0, initial = 0)
	num31 = forms.IntegerField(label = "31", min_value = 0, initial = 0)
	num32 = forms.IntegerField(label = "32", min_value = 0, initial = 0)
	num33 = forms.IntegerField(label = "33", min_value = 0, initial = 0)
	num34 = forms.IntegerField(label = "34", min_value = 0, initial = 0)
	num35 = forms.IntegerField(label = "35", min_value = 0, initial = 0)
	num36 = forms.IntegerField(label = "36", min_value = 0, initial = 0)
	num37 = forms.IntegerField(label = "37", min_value = 0, initial = 0)
	num38 = forms.IntegerField(label = "38", min_value = 0, initial = 0)
	num39 = forms.IntegerField(label = "39", min_value = 0, initial = 0)
	num40 = forms.IntegerField(label = "40", min_value = 0, initial = 0)
	num41 = forms.IntegerField(label = "41", min_value = 0, initial = 0)
	num42 = forms.IntegerField(label = "42", min_value = 0, initial = 0)
	num43 = forms.IntegerField(label = "43", min_value = 0, initial = 0)
	num44 = forms.IntegerField(label = "44", min_value = 0, initial = 0)
	num45 = forms.IntegerField(label = "45", min_value = 0, initial = 0)
	num46 = forms.IntegerField(label = "46", min_value = 0, initial = 0)
	num47 = forms.IntegerField(label = "47", min_value = 0, initial = 0)
	num48 = forms.IntegerField(label = "48", min_value = 0, initial = 0)
	num49 = forms.IntegerField(label = "49", min_value = 0, initial = 0)

class OddEvenForm(forms.Form):
	num1 = forms.IntegerField(label = "单", min_value = 0, initial = 0)
	num2 = forms.IntegerField(label = "双", min_value = 0, initial = 0)

class Animal6Form(forms.Form):
	num1 = forms.BooleanField(label = "猴(01,13,25,37,49)", required = False)
	num2 = forms.BooleanField(label = "羊(02,14,26,38)", required = False)
	num3 = forms.BooleanField(label = "马(03,15,27,39)", required = False)
	num4 = forms.BooleanField(label = "蛇(04,16,28,40)", required = False)
	num5 = forms.BooleanField(label = "龙(05,17,29,41)", required = False)
	num6 = forms.BooleanField(label = "兔(06,18,30,42)", required = False)
	num7 = forms.BooleanField(label = "虎(07,19,31,43)", required = False)
	num8 = forms.BooleanField(label = "牛(08,20,32,44)", required = False)
	num9 = forms.BooleanField(label = "鼠(09,21,33,45)", required = False)
	num10 = forms.BooleanField(label = "猪(10,22,34,46)", required = False)
	num11 = forms.BooleanField(label = "狗(11,23,35,47)", required = False)
	num12 = forms.BooleanField(label = "鸡(12,24,36,48)", required = False)
	money = forms.IntegerField(label = "金额", min_value = 0, initial = 0)



class AnimalForm(forms.Form):
	num1 = forms.IntegerField(label = "猴(01,13,25,37,49)", min_value = 0, initial = 0)
	num2 = forms.IntegerField(label = "羊(02,14,26,38)", min_value = 0, initial = 0)
	num3 = forms.IntegerField(label = "马(03,15,27,39)", min_value = 0, initial = 0)
	num4 = forms.IntegerField(label = "蛇(04,16,28,40)", min_value = 0, initial = 0)
	num5 = forms.IntegerField(label = "龙(05,17,29,41)", min_value = 0, initial = 0)
	num6 = forms.IntegerField(label = "兔(06,18,30,42)", min_value = 0, initial = 0)
	num7 = forms.IntegerField(label = "虎(07,19,31,43)", min_value = 0, initial = 0)
	num8 = forms.IntegerField(label = "牛(08,20,32,44)", min_value = 0, initial = 0)
	num9 = forms.IntegerField(label = "鼠(09,21,33,45)", min_value = 0, initial = 0)
	num10 = forms.IntegerField(label = "猪(10,22,34,46)", min_value = 0, initial = 0)
	num11 = forms.IntegerField(label = "狗(11,23,35,47)", min_value = 0, initial = 0)
	num12 = forms.IntegerField(label = "鸡(12,24,36,48)", min_value = 0, initial = 0)


class BigSmallForm(forms.Form):
	num1 = forms.IntegerField(label = "小数01~24", min_value = 0, initial = 0)
	num2 = forms.IntegerField(label = "大数25~49", min_value = 0, initial = 0)

class NormalAnimalForm(forms.Form):
	num1 = forms.IntegerField(label = "猴(01,13,25,37,49)", min_value = 0, initial = 0)
	num2 = forms.IntegerField(label = "羊(02,14,26,38)", min_value = 0, initial = 0)
	num3 = forms.IntegerField(label = "马(03,15,27,39)", min_value = 0, initial = 0)
	num4 = forms.IntegerField(label = "蛇(04,16,28,40)", min_value = 0, initial = 0)
	num5 = forms.IntegerField(label = "龙(05,17,29,41)", min_value = 0, initial = 0)
	num6 = forms.IntegerField(label = "兔(06,18,30,42)", min_value = 0, initial = 0)
	num7 = forms.IntegerField(label = "虎(07,19,31,43)", min_value = 0, initial = 0)
	num8 = forms.IntegerField(label = "牛(08,20,32,44)", min_value = 0, initial = 0)
	num9 = forms.IntegerField(label = "鼠(09,21,33,45)", min_value = 0, initial = 0)
	num10 = forms.IntegerField(label = "猪(10,22,34,46)", min_value = 0, initial = 0)
	num11 = forms.IntegerField(label = "狗(11,23,35,47)", min_value = 0, initial = 0)
	num12 = forms.IntegerField(label = "鸡(12,24,36,48)", min_value = 0, initial = 0)

class BuyCountForm(forms.Form):
	num1 = forms.FloatField(label = "01", min_value = 0, initial = 0)
	num2 = forms.FloatField(label = "02", min_value = 0, initial = 0)
	num3 = forms.FloatField(label = "03", min_value = 0, initial = 0)
	num4 = forms.FloatField(label = "04", min_value = 0, initial = 0)
	num5 = forms.FloatField(label = "05", min_value = 0, initial = 0)
	num6 = forms.FloatField(label = "06", min_value = 0, initial = 0)
	num7 = forms.FloatField(label = "07", min_value = 0, initial = 0)
	num8 = forms.FloatField(label = "08", min_value = 0, initial = 0)
	num9 = forms.FloatField(label = "09", min_value = 0, initial = 0)
	num10 = forms.FloatField(label = "10", min_value = 0, initial = 0)
	num11 = forms.FloatField(label = "11", min_value = 0, initial = 0)
	num12 = forms.FloatField(label = "12", min_value = 0, initial = 0)
	num13 = forms.FloatField(label = "13", min_value = 0, initial = 0)
	num14 = forms.FloatField(label = "14", min_value = 0, initial = 0)
	num15 = forms.FloatField(label = "15", min_value = 0, initial = 0)
	num16 = forms.FloatField(label = "16", min_value = 0, initial = 0)
	num17 = forms.FloatField(label = "17", min_value = 0, initial = 0)
	num18 = forms.FloatField(label = "18", min_value = 0, initial = 0)
	num19 = forms.FloatField(label = "19", min_value = 0, initial = 0)
	num20 = forms.FloatField(label = "20", min_value = 0, initial = 0)
	num21 = forms.FloatField(label = "21", min_value = 0, initial = 0)
	num22 = forms.FloatField(label = "22", min_value = 0, initial = 0)
	num23 = forms.FloatField(label = "23", min_value = 0, initial = 0)
	num24 = forms.FloatField(label = "24", min_value = 0, initial = 0)
	num25 = forms.FloatField(label = "25", min_value = 0, initial = 0)
	num26 = forms.FloatField(label = "26", min_value = 0, initial = 0)
	num27 = forms.FloatField(label = "27", min_value = 0, initial = 0)
	num28 = forms.FloatField(label = "28", min_value = 0, initial = 0)
	num29 = forms.FloatField(label = "29", min_value = 0, initial = 0)
	num30 = forms.FloatField(label = "30", min_value = 0, initial = 0)
	num31 = forms.FloatField(label = "31", min_value = 0, initial = 0)
	num32 = forms.FloatField(label = "32", min_value = 0, initial = 0)
	num33 = forms.FloatField(label = "33", min_value = 0, initial = 0)
	num34 = forms.FloatField(label = "34", min_value = 0, initial = 0)
	num35 = forms.FloatField(label = "35", min_value = 0, initial = 0)
	num36 = forms.FloatField(label = "36", min_value = 0, initial = 0)
	num37 = forms.FloatField(label = "37", min_value = 0, initial = 0)
	num38 = forms.FloatField(label = "38", min_value = 0, initial = 0)
	num39 = forms.FloatField(label = "39", min_value = 0, initial = 0)
	num40 = forms.FloatField(label = "40", min_value = 0, initial = 0)
	num41 = forms.FloatField(label = "41", min_value = 0, initial = 0)
	num42 = forms.FloatField(label = "42", min_value = 0, initial = 0)
	num43 = forms.FloatField(label = "43", min_value = 0, initial = 0)
	num44 = forms.FloatField(label = "44", min_value = 0, initial = 0)
	num45 = forms.FloatField(label = "45", min_value = 0, initial = 0)
	num46 = forms.FloatField(label = "46", min_value = 0, initial = 0)
	num47 = forms.FloatField(label = "47", min_value = 0, initial = 0)
	num48 = forms.FloatField(label = "48", min_value = 0, initial = 0)
	num49 = forms.FloatField(label = "49", min_value = 0, initial = 0)

class DepositForm(forms.Form):
	BankCard = forms.CharField(label = "银行卡号", max_length = 32, min_length = 4)
	Name = forms.CharField(label = "持卡人姓名", max_length = 10, min_length = 2)
	Money = forms.IntegerField(label = "提现金额", min_value = 100, initial = 0)
