# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('opentime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-vol'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('vol', models.IntegerField(default=0)),
                ('wonmoney', models.IntegerField(default=0)),
                ('ordertime', models.DateTimeField(default=django.utils.timezone.now)),
                ('totalmoney', models.IntegerField(default=0)),
                ('ordertype', models.IntegerField(default=0)),
                ('nums', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('level', models.IntegerField(default=0, verbose_name='级别')),
                ('money', models.FloatField(default=0.0, verbose_name='账户余额')),
                ('profit', models.FloatField(default=0.0, verbose_name='反水')),
            ],
        ),
    ]
