# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160512_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='betorder',
            name='hascount',
            field=models.BooleanField(default=False),
        ),
    ]
