# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_betorder_hascount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bindusername', models.CharField(max_length=20, verbose_name='用户名')),
                ('code', models.CharField(max_length=20, verbose_name='邀请码')),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profitusername',
            field=models.CharField(default='', max_length=20, verbose_name='提成至用户'),
        ),
    ]
