# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160513_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gifmoney',
            field=models.FloatField(default=0.0, verbose_name='赠金'),
        ),
    ]
