# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_userinfo_gifmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='gifmoney',
            new_name='giftmoney',
        ),
    ]
