# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160513_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opennum',
            name='result',
            field=models.CharField(default='', max_length=32),
        ),
    ]
