# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20160513_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opennum',
            name='result',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profitusername',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='提成至用户'),
        ),
    ]
