# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160516_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='opennum',
            name='bettype',
            field=models.IntegerField(choices=[(0, 'liuhe')], default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rebateprofit',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='rebateprofit'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profit',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='profit'),
        ),
    ]
