# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160517_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitioncode',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
