# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_invitioncode_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betorder',
            name='wonmoney',
            field=models.FloatField(default=0),
        ),
    ]
