# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20160519_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='betorder',
            name='rebate',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
