# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_betorder_rebate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('billtype', models.IntegerField(choices=[(0, '充值')], default=0)),
                ('username', models.CharField(max_length=20)),
                ('operateuser', models.CharField(max_length=20, verbose_name='操作用户')),
            ],
        ),
    ]
