# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='username',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
