# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20160524_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitioncode',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='credit',
            field=models.FloatField(default=0.0, verbose_name='可透支额度'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billtype',
            field=models.IntegerField(choices=[(0, '充值'), (1, '提现')], default=0),
        ),
    ]
