# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20160524_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitioncode',
            name='group',
            field=models.IntegerField(default=0, verbose_name='组别'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='group',
            field=models.IntegerField(default=0, verbose_name='组别'),
        ),
    ]
