# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20160527_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('money', models.FloatField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, '审核中'), (2, '处理中'), (3, '成功')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bindcard',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='银行卡'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billtype',
            field=models.IntegerField(choices=[(0, '充值'), (1, '提现'), (2, '给他人转账'), (3, '他人给你转账')], default=0),
        ),
    ]
