# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_deposit_bankcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='hasreturn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.IntegerField(choices=[(1, '审核中'), (2, '处理中'), (3, '成功'), (4, '失败')], default=0),
        ),
    ]
