# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20160602_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitioncode',
            name='rebate',
            field=models.FloatField(default=0, verbose_name='已获得提成'),
        ),
        migrations.AddField(
            model_name='invitioncode',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='totalbuy',
            field=models.IntegerField(default=0, verbose_name='购买总数'),
        ),
        migrations.AlterField(
            model_name='invitioncode',
            name='bindusername',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='用户名'),
        ),
    ]
