# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20160603_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitioncode',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invitioncode',
            name='bindusername',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='利益用户'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='totalbuy',
            field=models.IntegerField(default=0, verbose_name='已消费'),
        ),
    ]
