# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20160606_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='loginfailcount',
            field=models.IntegerField(default=0, verbose_name='登录失败次数'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='loginfailtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次失败时间'),
        ),
    ]
